// <auto-generated />
using GameAcademy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(GameAcademyDBContext))]
    [Migration("20221130033247_UpdateUserBag")]
    partial class UpdateUserBag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("GameAcademy.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GameAcademy.Models.GameRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("gameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastMovePlayer1")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastMovePlayer2")
                        .HasColumnType("TEXT");

                    b.Property<string>("player1")
                        .HasColumnType("TEXT");

                    b.Property<string>("player2")
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("GameRecords");
                });

            modelBuilder.Entity("GameAcademy.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("userName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("userName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GameAcademy.Models.User", b =>
                {
                    b.Property<string>("userName")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameAcademy.Models.Product", b =>
                {
                    b.HasOne("GameAcademy.Models.User", null)
                        .WithMany("BagItems")
                        .HasForeignKey("userName");
                });

            modelBuilder.Entity("GameAcademy.Models.User", b =>
                {
                    b.Navigation("BagItems");
                });
#pragma warning restore 612, 618
        }
    }
}
